version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/golang:1.17.5
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: sudo apt-get update && sudo apt upgrade -y
      - run: go get -v -t -d ./...
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: mkdir junit
      - run:
          command: |
            go test -cover -coverprofile=c.out -v ./... 2>&1 | go-junit-report > junit/report.xml
            mv c.out /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/c.out
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: ./junit