# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: mkdir junit
      - run: go test -v ./... 2>&1 | go-junit-report > junit/report.xml
      - store_test_results:
          path: ./junit